language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

install:
  - npm install -g serverless-cloud-framework
  - npm install

script:
  - npm run build

after_script:
  - touch .env
  - echo TENCENT_SECRET_ID=${TENCENT_SECRET_ID} >> .env
  - echo TENCENT_SECRET_KEY=${TENCENT_SECRET_KEY} >> .env
  - scf deploy --debug

branches:
  only:
    - master
    
notifications:
  email:
    on_success: always
    on_failure: always
