module.exports = [
  'bff 架构开发模式',
  'bff架构部署',
  'bff架构创建',
  'bff架构构建',
  'bff架构教程',
  'bff架构接口',
  'bff架构开发',
  'bff架构开发工具',
  'bff架构框架',
  'bff架构配置',
  'bff架构文档',
  'client side render',
  'csr',
  'egg.js',
  'egg.js官网',
  'egg.js教程',
  'egg.js框架',
  'egg.js入门',
  'egg.js文档',
  'express 应用创建',
  'express 中文手册',
  'express 中文文档',
  'express.js',
  'expressjs',
  'expressjS教程',
  'faas',
  'faas 架构',
  'faas技术框架',
  'faas实现',
  'go',
  'go工具',
  'go框架',
  'java',
  'java restful api',
  'java restful api 调用',
  'Javascript',
  'Javascript工具',
  'Javascript框架',
  'java工具',
  'java框架',
  'java调用restful api',
  'koa',
  'koa 教程',
  'koa 入门',
  'koa 文档',
  'koajs',
  'koajs 教程',
  'koajs 入门',
  'nest.js',
  'nestjs',
  'next.js',
  'nextjs',
  'node.js',
  'nodejs',
  'nodejs ssr',
  'nodejs 服务器',
  'nodejs 项目',
  'nodejs部署',
  'nodejs创建',
  'nodejs工具',
  'nodejs构建',
  'nodejs教程',
  'nodejs接口',
  'nodejs开发',
  'nodejs开发bff',
  'nodejs开发工具',
  'nodejs框架',
  'nodejs配置',
  'nodejs前端框架',
  'nodejs文档',
  'nuxt.js',
  'pg sql',
  'php',
  'php laravel',
  'php laravel教程',
  'php laravel框架',
  'php laravel文档',
  'php laravel文档',
  'postgresql',
  'python',
  'python flask',
  'python flask 安装',
  'python flask 教程',
  'python flask 框架',
  'python flask 模块',
  'python flask 日志',
  'python工具',
  'python框架',
  'react',
  'react ssr',
  'react.js',
  'react.js官网',
  'react.js教程',
  'react.js前后端',
  'react.js文档',
  'reactjs',
  'rest api',
  'rest api 教程',
  'rest api 接口',
  'rest api 开发',
  'rest api 文档',
  'restful api 实例',
  'restful api 调试工具',
  'restful api 调用',
  'restful api 文档',
  'restful api 文档工具',
  'restful api部署',
  'restful api创建',
  'restful api构建',
  'restful api教程',
  'restful api接口',
  'restful api接口规范',
  'restful api开发',
  'restful api开发工具',
  'restful api框架',
  'restful api配置',
  'restful api设计',
  'restful api实践',
  'restful api实现',
  'restful api文档',
  'restfulapi接口开发',
  'restfulapi开发',
  'restfulapi文档服务',
  'server side render',
  'serverless',
  'serverless bff',
  'serverless cloud function',
  'serverless faas',
  'serverless framework',
  'serverless ssr',
  'serverless 实战',
  'serverless安全',
  'serverless技术方案',
  'serverless架构',
  'serverless开源',
  'serverless框架',
  'serverless入门',
  'serverless实战',
  'serverless腾讯云',
  'serverless无服务器框架',
  'serverless无服务器云函数',
  'serverless无服务应用架构',
  'serverless下一代架构',
  'serverless应用',
  'serverless云函数架构',
  'single page application',
  'spa',
  'ssr',
  'tencent云 faas',
  'vercel',
  'vue',
  'vue ssr',
  'vue.js',
  'vue.js官网',
  'vue.js教程',
  'vue.js前后端',
  'vue.js文档',
  'vue.js语法',
  'vuejs',
  'webpack',
  'website',
  'website 组件',
  'web前端开发工具',
  'web前端开发教程',
  'web前端开发接口',
  'web前端开发框架',
  'web前端开发配置',
  'web前端开发文档',
  'web前端应用部署',
  'zeit',
  '阿里云函数计算',
  '创建nodejs项目',
  '搭建restful api后台',
  '搭建serverless',
  '单页应用',
  '服务端渲染',
  '服务器端渲染',
  '功能即服务(faas)',
  '构建restful api',
  '函数即服务(faas)',
  '函数计算',
  '函数计算阿里云',
  '函数计算服务',
  '函数计算服务器',
  '客户端渲染',
  '前端开发工具',
  '前端开发教程',
  '前端开发接口',
  '前端开发框架',
  '前端开发配置',
  '前端开发文档',
  '前端应用部署',
  '深入浅出serverless',
  '首屏加载优化',
  '首屏性能优化',
  '腾讯云 serverless framework',
  '腾讯云faas',
  '腾讯云serverless',
  '腾讯云serverless cloud function',
  '腾讯云serverless framework',
  '腾讯云serverless 实战',
  '腾讯云serverless安全',
  '腾讯云serverless技术方案',
  '腾讯云serverless架构',
  '腾讯云serverless框架',
  '腾讯云serverless入门',
  '腾讯云serverless实战',
  '腾讯云serverless无服务器框架',
  '腾讯云serverless下一代架构',
  '腾讯云serverless应用',
  '腾讯云ssr',
  '腾讯云搭建serverless',
  '腾讯云函数计算',
  '腾讯云函数计算服务器',
  '腾讯云深入浅出serverless',
  '腾讯云无服务器计算',
  '腾讯云无服务器架构',
  '腾讯云无服务器云函数',
  '腾讯云自建serverless',
  '同构渲染',
  '无服务器',
  '无服务器函数',
  '无服务器计算',
  '无服务器架构',
  '无服务器开发',
  '无服务器应该框架',
  '无服务器云功能',
  '无服务器云函数',
  '一站式serverless应用开发服务',
  '云函数',
  '云函数scf无服务器架构',
  '云原生',
  '运行nodejs项目',
  '自建serverless',
  '组件化开发',
]
